
package soap.tim7.services.banka;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-08-22T23:27:53.449+02:00
 * Generated source version: 2.6.5
 * 
 */
 
public class Banka_BankaPort_Server{
	//prima deo adrese da bi instancirao
    protected Banka_BankaPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new BankaImpl();
        String address = "http://localhost:8080/Banka";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new Banka_BankaPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
