
package soap.tim7.services.banka;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-08-22T23:27:53.318+02:00
 * Generated source version: 2.6.5
 */

@WebFault(name = "return_status", targetNamespace = "http://xws/tim7/globals")
public class StatusMessage extends Exception {
    
    private soap.tim7.entities.globals.ReturnStatus returnStatus;

    public StatusMessage() {
        super();
    }
    
    public StatusMessage(String message) {
        super(message);
    }
    
    public StatusMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public StatusMessage(String message, soap.tim7.entities.globals.ReturnStatus returnStatus) {
        super(message);
        this.returnStatus = returnStatus;
    }

    public StatusMessage(String message, soap.tim7.entities.globals.ReturnStatus returnStatus, Throwable cause) {
        super(message, cause);
        this.returnStatus = returnStatus;
    }

    public soap.tim7.entities.globals.ReturnStatus getFaultInfo() {
        return this.returnStatus;
    }
}
