//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.19 at 05:48:45 PM CEST 
//


package xws.tim7.entities.firma;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID_firme" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="Naziv_firme" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Adresa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Sajt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Partneri" type="{http://xws/tim7/firma}TPartneri"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idFirme",
    "nazivFirme",
    "adresa",
    "sajt",
    "partneri"
})
@XmlRootElement(name = "Firma")
public class Firma {

    @XmlElement(name = "ID_firme")
    protected long idFirme;
    @XmlElement(name = "Naziv_firme", required = true)
    protected String nazivFirme;
    @XmlElement(name = "Adresa", required = true)
    protected String adresa;
    @XmlElement(name = "Sajt", required = true)
    protected String sajt;
    @XmlElement(name = "Partneri", required = true)
    protected TPartneri partneri;

    /**
     * Gets the value of the idFirme property.
     * 
     */
    public long getIDFirme() {
        return idFirme;
    }

    /**
     * Sets the value of the idFirme property.
     * 
     */
    public void setIDFirme(long value) {
        this.idFirme = value;
    }

    /**
     * Gets the value of the nazivFirme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivFirme() {
        return nazivFirme;
    }

    /**
     * Sets the value of the nazivFirme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivFirme(String value) {
        this.nazivFirme = value;
    }

    /**
     * Gets the value of the adresa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdresa() {
        return adresa;
    }

    /**
     * Sets the value of the adresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdresa(String value) {
        this.adresa = value;
    }

    /**
     * Gets the value of the sajt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSajt() {
        return sajt;
    }

    /**
     * Sets the value of the sajt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSajt(String value) {
        this.sajt = value;
    }

    /**
     * Gets the value of the partneri property.
     * 
     * @return
     *     possible object is
     *     {@link TPartneri }
     *     
     */
    public TPartneri getPartneri() {
        return partneri;
    }

    /**
     * Sets the value of the partneri property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPartneri }
     *     
     */
    public void setPartneri(TPartneri value) {
        this.partneri = value;
    }

}
