//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.22 at 02:30:22 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xws/tim7/firma", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package soap.tim7.entities.firma;
