package xws.tim7.services.banka;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-08-22T23:27:53.434+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(targetNamespace = "http://xws/tim7/banka", name = "Banka")
@XmlSeeAlso({xws.tim7.entities.mt102.ObjectFactory.class, xws.tim7.entities.mt910.ObjectFactory.class, xws.tim7.entities.nalogzaplacanje.ObjectFactory.class, xws.tim7.entities.mt900.ObjectFactory.class, xws.tim7.entities.globals.ObjectFactory.class, xws.tim7.entities.presek.ObjectFactory.class, xws.tim7.entities.zahtevzaizvod.ObjectFactory.class, xws.tim7.entities.mt103.ObjectFactory.class})
public interface Banka {

    @WebMethod
    @Oneway
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void obaviClearing();

    @WebMethod
    @RequestWrapper(localName = "primiNalogZaPlacanje", targetNamespace = "http://xws/tim7/nalogZaPlacanje", className = "xws.tim7.nalogzaplacanje.PrimiNalogZaPlacanje")
    @ResponseWrapper(localName = "return_status", targetNamespace = "http://xws/tim7/globals", className = "xws.tim7.globals.ReturnStatus")
    @WebResult(name = "status", targetNamespace = "http://xws/tim7/globals")
    public xws.tim7.entities.globals.StatusType primiNalogZaPlacanje(
        @WebParam(name = "nalog_za_placanje", targetNamespace = "http://xws/tim7/nalogZaPlacanje")
        xws.tim7.entities.nalogzaplacanje.NalogZaPlacanjeType nalogZaPlacanje
    );

    @WebMethod
    @RequestWrapper(localName = "primiMT900", targetNamespace = "http://xws/tim7/mt900", className = "xws.tim7.mt900.PrimiMT900")
    @ResponseWrapper(localName = "return_status", targetNamespace = "http://xws/tim7/globals", className = "xws.tim7.globals.ReturnStatus")
    @WebResult(name = "status", targetNamespace = "http://xws/tim7/globals")
    public xws.tim7.entities.globals.StatusType primiMT900(
        @WebParam(name = "poruka_o_zaduzenju_MT900", targetNamespace = "http://xws/tim7/mt900")
        xws.tim7.entities.globals.MT9XXType porukaOZaduzenjuMT900
    );

    @WebMethod
    @RequestWrapper(localName = "primiMT910", targetNamespace = "http://xws/tim7/mt910", className = "xws.tim7.mt910.PrimiMT910")
    @ResponseWrapper(localName = "return_status", targetNamespace = "http://xws/tim7/globals", className = "xws.tim7.globals.ReturnStatus")
    @WebResult(name = "status", targetNamespace = "http://xws/tim7/globals")
    public xws.tim7.entities.globals.StatusType primiMT910(
        @WebParam(name = "poruka_o_odobrenju_MT910", targetNamespace = "http://xws/tim7/mt910")
        xws.tim7.entities.globals.MT9XXType porukaOOdobrenjuMT910
    );

    @WebMethod
    @RequestWrapper(localName = "primiZahtevZaIzvod", targetNamespace = "http://xws/tim7/zahtevZaIzvod", className = "xws.tim7.zahtevzaizvod.PrimiZahtevZaIzvod")
    @ResponseWrapper(localName = "return_presek", targetNamespace = "http://xws/tim7/presek", className = "xws.tim7.presek.ReturnPresek")
    @WebResult(name = "presek", targetNamespace = "http://xws/tim7/presek")
    public xws.tim7.entities.presek.PresekType primiZahtevZaIzvod(
        @WebParam(name = "zahtev_za_izvod", targetNamespace = "http://xws/tim7/zahtevZaIzvod")
        xws.tim7.entities.zahtevzaizvod.ZahtevZaIzvodType zahtevZaIzvod
    ) throws StatusMessage;

    @WebMethod
    @RequestWrapper(localName = "primiMT103", targetNamespace = "http://xws/tim7/mt103", className = "xws.tim7.mt103.PrimiMT103")
    @ResponseWrapper(localName = "return_status", targetNamespace = "http://xws/tim7/globals", className = "xws.tim7.globals.ReturnStatus")
    @WebResult(name = "status", targetNamespace = "http://xws/tim7/globals")
    public xws.tim7.entities.globals.StatusType primiMT103(
        @WebParam(name = "RTGS_MT103", targetNamespace = "http://xws/tim7/mt103")
        xws.tim7.entities.mt103.MT103Type rtgsMT103
    );

    @WebMethod
    @RequestWrapper(localName = "primiMT102", targetNamespace = "http://xws/tim7/mt102", className = "xws.tim7.mt102.PrimiMT102")
    @ResponseWrapper(localName = "return_status", targetNamespace = "http://xws/tim7/globals", className = "xws.tim7.globals.ReturnStatus")
    @WebResult(name = "status", targetNamespace = "http://xws/tim7/globals")
    public xws.tim7.entities.globals.StatusType primiMT102(
        @WebParam(name = "nalog_za_grupna_placanja", targetNamespace = "http://xws/tim7/mt102")
        xws.tim7.entities.mt102.MT102Type nalogZaGrupnaPlacanja
    );
}
