
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package xws.tim7.banka;

import java.util.logging.Logger;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-08-22T23:27:53.404+02:00
 * Generated source version: 2.6.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "BankaService",
                      portName = "BankaPort",
                      targetNamespace = "http://xws/tim7/banka",
                      wsdlLocation = "file:/D:/Programiranje/Eclipse workspaces/XWS/XWS_Tim7/WEB-INF/wsdl/banka.wsdl",
                      endpointInterface = "xws.tim7.banka.Banka")
                      
public class BankaImpl implements Banka {

    private static final Logger LOG = Logger.getLogger(BankaImpl.class.getName());

    /* (non-Javadoc)
     * @see xws.tim7.banka.Banka#obaviClearing(*
     */
    public void obaviClearing() { 
        LOG.info("Executing operation obaviClearing");
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see xws.tim7.banka.Banka#primiNalogZaPlacanje(xws.tim7.nalogzaplacanje.NalogZaPlacanjeType  nalogZaPlacanje )*
     */
    public xws.tim7.globals.StatusType primiNalogZaPlacanje(xws.tim7.nalogzaplacanje.NalogZaPlacanjeType nalogZaPlacanje) { 
        LOG.info("Executing operation primiNalogZaPlacanje");
        System.out.println(nalogZaPlacanje);
        try {
            xws.tim7.globals.StatusType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see xws.tim7.banka.Banka#primiMT900(xws.tim7.globals.MT9XXType  porukaOZaduzenjuMT900 )*
     */
    public xws.tim7.globals.StatusType primiMT900(xws.tim7.globals.MT9XXType porukaOZaduzenjuMT900) { 
        LOG.info("Executing operation primiMT900");
        System.out.println(porukaOZaduzenjuMT900);
        try {
            xws.tim7.globals.StatusType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see xws.tim7.banka.Banka#primiMT910(xws.tim7.globals.MT9XXType  porukaOOdobrenjuMT910 )*
     */
    public xws.tim7.globals.StatusType primiMT910(xws.tim7.globals.MT9XXType porukaOOdobrenjuMT910) { 
        LOG.info("Executing operation primiMT910");
        System.out.println(porukaOOdobrenjuMT910);
        try {
            xws.tim7.globals.StatusType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see xws.tim7.banka.Banka#primiZahtevZaIzvod(xws.tim7.zahtevzaizvod.ZahtevZaIzvodType  zahtevZaIzvod )*
     */
    public xws.tim7.presek.PresekType primiZahtevZaIzvod(xws.tim7.zahtevzaizvod.ZahtevZaIzvodType zahtevZaIzvod) throws StatusMessage    { 
        LOG.info("Executing operation primiZahtevZaIzvod");
        System.out.println(zahtevZaIzvod);
        try {
            xws.tim7.presek.PresekType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new StatusMessage("statusMessage...");
    }

    /* (non-Javadoc)
     * @see xws.tim7.banka.Banka#primiMT103(xws.tim7.mt103.MT103Type  rtgsMT103 )*
     */
    public xws.tim7.globals.StatusType primiMT103(xws.tim7.mt103.MT103Type rtgsMT103) { 
        LOG.info("Executing operation primiMT103");
        System.out.println(rtgsMT103);
        try {
            xws.tim7.globals.StatusType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see xws.tim7.banka.Banka#primiMT102(xws.tim7.mt102.MT102Type  nalogZaGrupnaPlacanja )*
     */
    public xws.tim7.globals.StatusType primiMT102(xws.tim7.mt102.MT102Type nalogZaGrupnaPlacanja) { 
        LOG.info("Executing operation primiMT102");
        System.out.println(nalogZaGrupnaPlacanja);
        try {
            xws.tim7.globals.StatusType _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
