package xws.tim7.banka;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import xws.tim7.faktura.Faktura;
import xws.tim7.globals.RacunType;
import xws.tim7.globals.StatusType;
import xws.tim7.nalogzaplacanje.NalogZaPlacanjeType;
import xws.tim7.presek.PresekType;
import xws.tim7.zahtevzaizvod.ZahtevZaIzvodType;

/**
 * This class was generated by Apache CXF 2.6.5 2015-08-22T23:27:53.155+02:00
 * Generated source version: 2.6.5
 * 
 */
public final class Banka_BankaPort_Client {

	private static final QName SERVICE_NAME = new QName(
			"http://xws/tim7/banka", "BankaService");
	private String wsdlPart = "http://localhost:8080/Banka/%s?wsdl";
	private String racun;

	public Banka_BankaPort_Client(String racun) {
		this.racun = racun;			// racun korisnika, preko njega odredjujemo banku
	}

	private Banka getService() {
		Banka port = null;
		try {
			URL wsdlURL = new URL(String.format(wsdlPart, racun.substring(0, 3)));
			BankaService ss = new BankaService(wsdlURL, SERVICE_NAME);
			port = ss.getBankaPort();
			return port;
		} catch (MalformedURLException e) {
			// TODO LOG ERROR
			e.printStackTrace();
		}
		return port;
	}
	
	public StatusType posaljiNalogZaPlacanje(Faktura faktura) {
		Banka banka = this.getService();		
		xws.tim7.nalogzaplacanje.ObjectFactory factory =  new xws.tim7.nalogzaplacanje.ObjectFactory();
		NalogZaPlacanjeType nzp = factory.createNalogZaPlacanjeType(faktura, racun);
		return banka.primiNalogZaPlacanje(nzp);
	}

	public PresekType primiZahtevZaIzvod(XMLGregorianCalendar date, int redniBroj) {
		xws.tim7.zahtevzaizvod.ObjectFactory factory = new xws.tim7.zahtevzaizvod.ObjectFactory();
		ZahtevZaIzvodType zahtevZaIzvod = factory.createZahtevZaIzvodType(racun, date, redniBroj);
		Banka banka = this.getService();
		PresekType retVal = null;
		try {
			retVal = banka.primiZahtevZaIzvod(zahtevZaIzvod);
		} catch (StatusMessage e) {
			// TODO LOG INFO
			e.printStackTrace();
		}
		return retVal;
	}
}
