
package xws.tim7.banka;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-08-22T23:27:53.155+02:00
 * Generated source version: 2.6.5
 * 
 */
public final class Banka_BankaPort_Client {

    private static final QName SERVICE_NAME = new QName("http://xws/tim7/banka", "BankaService");

    private Banka_BankaPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BankaService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BankaService ss = new BankaService(wsdlURL, SERVICE_NAME);
        Banka port = ss.getBankaPort();  
        
        {
        System.out.println("Invoking obaviClearing...");
        port.obaviClearing();


        }
        {
        System.out.println("Invoking primiNalogZaPlacanje...");
        xws.tim7.nalogzaplacanje.NalogZaPlacanjeType _primiNalogZaPlacanje_nalogZaPlacanje = null;
        xws.tim7.globals.StatusType _primiNalogZaPlacanje__return = port.primiNalogZaPlacanje(_primiNalogZaPlacanje_nalogZaPlacanje);
        System.out.println("primiNalogZaPlacanje.result=" + _primiNalogZaPlacanje__return);


        }
        {
        System.out.println("Invoking primiMT900...");
        xws.tim7.globals.MT9XXType _primiMT900_porukaOZaduzenjuMT900 = null;
        xws.tim7.globals.StatusType _primiMT900__return = port.primiMT900(_primiMT900_porukaOZaduzenjuMT900);
        System.out.println("primiMT900.result=" + _primiMT900__return);


        }
        {
        System.out.println("Invoking primiMT910...");
        xws.tim7.globals.MT9XXType _primiMT910_porukaOOdobrenjuMT910 = null;
        xws.tim7.globals.StatusType _primiMT910__return = port.primiMT910(_primiMT910_porukaOOdobrenjuMT910);
        System.out.println("primiMT910.result=" + _primiMT910__return);


        }
        {
        System.out.println("Invoking primiZahtevZaIzvod...");
        xws.tim7.zahtevzaizvod.ZahtevZaIzvodType _primiZahtevZaIzvod_zahtevZaIzvod = null;
        try {
            xws.tim7.presek.PresekType _primiZahtevZaIzvod__return = port.primiZahtevZaIzvod(_primiZahtevZaIzvod_zahtevZaIzvod);
            System.out.println("primiZahtevZaIzvod.result=" + _primiZahtevZaIzvod__return);

        } catch (StatusMessage e) { 
            System.out.println("Expected exception: statusMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking primiMT103...");
        xws.tim7.mt103.MT103Type _primiMT103_rtgsMT103 = null;
        xws.tim7.globals.StatusType _primiMT103__return = port.primiMT103(_primiMT103_rtgsMT103);
        System.out.println("primiMT103.result=" + _primiMT103__return);


        }
        {
        System.out.println("Invoking primiMT102...");
        xws.tim7.mt102.MT102Type _primiMT102_nalogZaGrupnaPlacanja = null;
        xws.tim7.globals.StatusType _primiMT102__return = port.primiMT102(_primiMT102_nalogZaGrupnaPlacanja);
        System.out.println("primiMT102.result=" + _primiMT102__return);


        }

        System.exit(0);
    }

}
