package xws.tim7.cb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-08-22T23:28:01.230+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(targetNamespace = "http://xws/tim7/cb", name = "CentralnaBanka")
@XmlSeeAlso({xws.tim7.mt102.ObjectFactory.class, xws.tim7.mt910.ObjectFactory.class, xws.tim7.nalogzaplacanje.ObjectFactory.class, xws.tim7.mt900.ObjectFactory.class, xws.tim7.globals.ObjectFactory.class, xws.tim7.mt103.ObjectFactory.class})
public interface CentralnaBanka {

    @WebMethod
    @RequestWrapper(localName = "primiMT102", targetNamespace = "http://xws/tim7/mt102", className = "xws.tim7.mt102.PrimiMT102")
    @ResponseWrapper(localName = "return_status", targetNamespace = "http://xws/tim7/globals", className = "xws.tim7.globals.ReturnStatus")
    @WebResult(name = "status", targetNamespace = "http://xws/tim7/globals")
    public xws.tim7.globals.StatusType primiMT102(
        @WebParam(name = "nalog_za_grupna_placanja", targetNamespace = "http://xws/tim7/mt102")
        xws.tim7.mt102.MT102Type nalogZaGrupnaPlacanja
    );

    @WebMethod
    @RequestWrapper(localName = "primiMT103", targetNamespace = "http://xws/tim7/mt103", className = "xws.tim7.mt103.PrimiMT103")
    @ResponseWrapper(localName = "return_status", targetNamespace = "http://xws/tim7/globals", className = "xws.tim7.globals.ReturnStatus")
    @WebResult(name = "status", targetNamespace = "http://xws/tim7/globals")
    public xws.tim7.globals.StatusType primiMT103(
        @WebParam(name = "RTGS_MT103", targetNamespace = "http://xws/tim7/mt103")
        xws.tim7.mt103.MT103Type rtgsMT103
    );
}
