
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package xws.tim7.cb;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2015-08-22T23:28:01.206+02:00
 * Generated source version: 2.6.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "CentralnaBankaService",
                      portName = "CentralnaBankaPort",
                      targetNamespace = "http://xws/tim7/cb",
                      wsdlLocation = "file://home/danex/Documents/Eclipse_workspaces/XWS/XWS_test/WEB-INF/wsdl/centralnaBanka.wsdl",
                      endpointInterface = "xws.tim7.cb.CentralnaBanka")
                      
public class CentralnaBankaImpl implements CentralnaBanka {

    private static final Logger LOG = Logger.getLogger(CentralnaBankaImpl.class.getName());

    /* (non-Javadoc)
     * @see xws.tim7.cb.CentralnaBanka#primiMT102(xws.tim7.mt102.MT102Type  nalogZaGrupnaPlacanja )*
     */
    public xws.tim7.globals.StatusType primiMT102(xws.tim7.mt102.MT102Type nalogZaGrupnaPlacanja) { 
        LOG.info("Executing operation primiMT102");
        System.out.println(nalogZaGrupnaPlacanja);
        try {
            xws.tim7.globals.StatusType _return = null;
            // MT102Dao.persist(clearingNalog);	//cuvaj pa periodicno radi clearing, ili radi odmah
        	// for(mt102 in MT102Dao.findAll()) {
        	//     BankaClient client = new BankaClient(mt102.getRacunDobavljaca());
        	//     client.primiMt102(mt102);
        	// }
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see xws.tim7.cb.CentralnaBanka#primiMT103(xws.tim7.mt103.MT103Type  rtgsMT103 )*
     */
    public xws.tim7.globals.StatusType primiMT103(xws.tim7.mt103.MT103Type rtgsMT103) { 
        LOG.info("Executing operation primiMT103");
        System.out.println(rtgsMT103);
        try {
            xws.tim7.globals.StatusType _return = null;
            // ObracunskiRacunDao.transferFunds(rtgsNalog.getObracunskiRacunBankeKupca(), rtgsNalog.getObracunskiRacunBankeDostavljaca(), rtgsNalog.getIznos());

        	// napravi Mt900
        	// BankaClient bankaKupca = new BankaClient(rtgsNalog.getObracunskiRacunBankeKupca());
        	// bankaKupca.primiMT900(mt900);
        	
        	// napravi Mt910
        	// BankaClient bankaDostavljaca = new BankaClient(rtgsNalog.getObracunskiRacunBankeDostavljaca());
        	// bankaDostavljaca.primitMT910(mt910);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
