//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.22 at 02:30:23 PM CEST 
//


package xws.tim7.entities.globals;

import java.math.BigDecimal;
import java.math.BigInteger;

import javax.xml.bind.annotation.XmlRegistry;

import xws.tim7.entities.faktura.Faktura;
import xws.tim7.entities.mt102.MT102Type;
import xws.tim7.entities.mt103.MT103Type;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xws.tim7.globals package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xws.tim7.globals
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReturnStatus }
     * 
     */
    public ReturnStatus createReturnStatus() {
        return new ReturnStatus();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link RacunType }
     * @param racunKupca 
     * 
     */
    public RacunType createRacunType(String racunKupca) {
        RacunType retVal = new RacunType();
        retVal.setBrojRacuna(racunKupca);
        retVal.setModel(new BigInteger("97"));	//nije dato u specifikaciji
        retVal.setPozivNaBroj(racunKupca);		//nije dato u specifikaciji
        return retVal;
    }

    /**
     * Create an instance of {@link OsnovaNalogaZaPlacanjeType }
     * 
     */
    public OsnovaNalogaZaPlacanjeType createOsnovaNalogaZaPlacanjeType() {
        return new OsnovaNalogaZaPlacanjeType();
    }

    /**
     * Create an instance of {@link OsnovaNalogaZaPlacanjeType }
     * 
     */
    public OsnovaNalogaZaPlacanjeType createOsnovaNalogaZaPlacanjeType(Faktura faktura, String racunKupca) {
        OsnovaNalogaZaPlacanjeType retVal = new OsnovaNalogaZaPlacanjeType();
        
        retVal.setDuznikNalogodavac(faktura.getZaglavlje().getKupac().getNaziv());
        retVal.setPoverilacPrimalac(faktura.getZaglavlje().getDobavljac().getNaziv());

        RacunType racunDuznika = this.createRacunType(racunKupca);
        RacunType racunPoverioca = this.createRacunType(faktura.getZaglavlje().getUplataNaRacun());
        
        retVal.setRacunDuznika(racunDuznika);
        retVal.setRacunPoverioca(racunPoverioca);
        
        BigDecimal iznos = faktura.getZaglavlje().getIznosZaUplatu();
        retVal.setIznos(iznos);
        String svrha = "";
        for(xws.tim7.entities.faktura.Stavka stavka : faktura.getStavka()) {
        	svrha += stavka.getNazivRobeIliUsluge() + " ";
        }
        retVal.setSvrhaPlacanja(svrha);
        
        return retVal;
    }
    /**
     * Create an instance of {@link MT9XXType }
     * 
     */
    public MT9XXType createMT9XXType() {
        return new MT9XXType();
    }

	public MT9XXType createMT900Type(MT103Type rtgsMT103) {

		MT9XXType retVal = new MT9XXType();
		
		retVal.setDatumValute(rtgsMT103.getDatumValute());
		retVal.setIDPoruke(rtgsMT103.getIDPoruke());
		retVal.setIDPorukeNaloga(rtgsMT103.getIDPoruke());
		retVal.setIznos(rtgsMT103.getOsnovaNalogaZaPlacanje().getIznos());
		retVal.setObracunskiRacunBanke(rtgsMT103.getObracunskiRacunBankeDuznika());
		retVal.setSifraValute(rtgsMT103.getSifraValute());
		retVal.setSWIFTKodBanke(rtgsMT103.getSWIFTKodBankeDuznika());
		
		return retVal;
	}
	
	public MT9XXType createMT910Type(MT103Type rtgsMT103) {
		MT9XXType retVal = new MT9XXType();
		
		retVal.setDatumValute(rtgsMT103.getDatumValute());
		retVal.setIDPoruke(rtgsMT103.getIDPoruke());
		retVal.setIDPorukeNaloga(rtgsMT103.getIDPoruke());
		retVal.setIznos(rtgsMT103.getOsnovaNalogaZaPlacanje().getIznos());
		retVal.setObracunskiRacunBanke(rtgsMT103.getObracunskiRacunBankePoverioca());
		retVal.setSifraValute(rtgsMT103.getSifraValute());
		retVal.setSWIFTKodBanke(rtgsMT103.getSWIFTKodBankePoverioca());
		
		return retVal;
	}

	public MT9XXType createMT900Type(MT102Type nalogZaGrupnaPlacanja) {
		MT9XXType retVal = new MT9XXType();
		
		retVal.setDatumValute(nalogZaGrupnaPlacanja.getDatumValute());
		
		return retVal;
	}

	public MT9XXType createMT910Type(MT102Type nalogZaGrupnaPlacanja) {
		MT9XXType retVal = new MT9XXType();
		
		
		return retVal;
	}


}
